Weather app
SamArsanios/weather-app pull request #1
Opened 2021-05-04 18:06 UTC by SamArsanios

In this project, I build a weather app that tells the user the current weather statistics of a given city. This project was built with Javascript. The API call is made from openweathermap.org

2021-05-04 20:53 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @SamArsanios  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented all of the requirements so carefully, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] The weather app should change its appearance based on the received data ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/appearance_requirement.png) from Odin)
- [ ] You sgould use ES6 syntax ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/weather_app/es6_requirement.png) from Pathwright)
    - [ ] usage of arrow functions instead of the function keyword
- [x] Kindly remove the commented codes
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2021-05-04 20:53 UTC, descholar-ceo commented on README.md
> +$ npm install
[optional] Please clarify what to do after `npm i`

2021-05-04 20:53 UTC, descholar-ceo commented on src/index.js
> +};
[required] Kindly remove all of the commented codes

2021-05-04 20:53 UTC, descholar-ceo commented on src/index.js
> +};
- [ ]  [required] usage of arrow functions instead of the function keyword

2021-05-04 20:53 UTC, descholar-ceo commented on src/weatherData.js
> +    // iconBig: `https://openweathermap.org/img/wn/${data.weather[0].icon}@4x.png`,
- [ ] [required] Kindly let's remove this commented codes

2021-05-04 20:53 UTC, descholar-ceo commented on src/weatherData.js
> +  // }
- [ ] [required] Kindly let's remove this commented codes

2021-05-05 07:10 UTC, mikenath223 approved these changes
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-05-05 07:14 UTC, merged